spring:
  application:
    name: reciping-like-service-BE
  data:
    mongodb:
      uri: mongodb://recipingadmin:changeme@reciping-nosql.cluster-c7wokrloy1td.ap-northeast-2.docdb.amazonaws.com:37017/like_service_db
  jackson:
    serialization:
      indent_output: true

jwt:
  secret:
    key: ${JWT_SECRET_KEY}